export type JobProfileStatus = 'ACTIVE' | 'DRAFT' | 'ARCHIVED';

export type JobProfileItemType = 'JP_UPLOAD' | 'JOBPROFILE';

export type JpUploadStatus = 'PENDING' | 'PARSING' | 'AI_PROCESSING' | 'DONE' | 'FAILED';

export interface JobProfile {
  id: string;
  title: string;
  categoryId: string;
  keywords: string[];
  description: string;
  requirements: string;
  /** canonical UI schema (label/value, stringified JSON) */
  aiProfileUiJson?: string | null;
  /** extras (label/value, stringified JSON) */
  aiExtrasJson?: string | null;
  rawJdText?: string | null;
  status: JobProfileStatus;
  createdAt: string;
  updatedAt: string;
}

/** Draft record stored in JobProfiles table (item_type = JP_UPLOAD). */
export interface JobProfileUpload {
  id: string;
  userId: string;
  filename: string;
  contentType: string;
  size: number;
  s3Key: string;
  url: string;
  status: JpUploadStatus;
  parseSource?: string | null;
  rawText?: string | null;
  /** candidate-facing JD description preview (generated by worker, editable by admin at finalize) */
  description?: string | null;
  aiProfileUiJson?: string | null; // canonical with {label,value} for UI
  aiExtrasJson?: string | null; // extras
  error?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface ListJobProfilesResult {
  items: JobProfile[];
  nextCursor?: string;
}

